# Generated by Django 5.1.1 on 2024-09-08 15:28

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="book",
            managers=[
                ("available_books", django.db.models.manager.Manager()),
            ],
        ),
    ]
