# Generated by Django 5.1.1 on 2024-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowedbook",
            old_name="return_by",
            new_name="return_date",
        ),
        migrations.AddField(
            model_name="borrowedbook",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
