# Generated by Django 5.1.1 on 2024-09-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_return_by_borrowedbook_return_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowedbook",
            name="number_of_days",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
